import { Transaction } from "./types";

export interface MonthlyReportData {
  month: string;
  total_income: number;
  total_expenses: number;
  net_cashflow: number;
  by_category?: Record<string, number>;
}

export interface GoalReport {
  name: string;
  type: string;
  target_amount: number;
  target_date: string;
  saved?: number;
}

export function exportToCSV(transactions: Transaction[], filename = "transactions.csv") {
  const headers = ["Date", "Merchant", "Description", "Category", "Amount", "Currency"];
  const rows = transactions.map((t) => [
    t.posted_at,
    t.merchant || "",
    `"${t.description.replace(/"/g, '""')}"`,
    t.category,
    t.amount.toFixed(2),
    t.currency || "USD",
  ]);

  const csv = [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");
  downloadBlob(csv, filename, "text/csv");
}

export function exportToPrintPDF() {
  window.print();
}

export function exportMonthlyReportPDF(summary: MonthlyReportData, goals: GoalReport[] = []) {
  const catRows = summary.by_category
    ? Object.entries(summary.by_category)
        .filter(([, v]) => v > 0)
        .sort((a, b) => b[1] - a[1])
        .map(([cat, amt]) => `<tr><td>${cat}</td><td style="text-align:right">$${amt.toFixed(2)}</td></tr>`)
        .join("")
    : "";
  const goalRows = goals
    .filter((g) => g.target_amount > 0)
    .map(
      (g) =>
        `<tr><td>${g.name || g.type}</td><td>$${g.target_amount.toFixed(0)}</td><td>${g.target_date}</td><td>${g.saved != null ? "$" + g.saved.toFixed(0) : "—"}</td></tr>`
    )
    .join("");
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Monthly Report ${summary.month}</title><style>
    body{font-family:system-ui,sans-serif;max-width:600px;margin:2rem auto;padding:1rem;color:#1e293b;}
    h1{font-size:1.25rem;} table{width:100%;border-collapse:collapse;} th,td{padding:0.5rem;border-bottom:1px solid #e2e8f0;} th{text-align:left;}
    .summary{display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1rem 0;}
    .card{background:#f8fafc;padding:1rem;border-radius:8px;}
  </style></head><body>
    <h1>Finance Report — ${summary.month}</h1>
    <div class="summary">
      <div class="card"><strong>Income</strong><br/>$${summary.total_income.toFixed(2)}</div>
      <div class="card"><strong>Expenses</strong><br/>$${summary.total_expenses.toFixed(2)}</div>
      <div class="card"><strong>Net cashflow</strong><br/>$${summary.net_cashflow.toFixed(2)}</div>
    </div>
    ${catRows ? `<h2>Spending by category</h2><table><thead><tr><th>Category</th><th>Amount</th></tr></thead><tbody>${catRows}</tbody></table>` : ""}
    ${goalRows ? `<h2>Goals</h2><table><thead><tr><th>Goal</th><th>Target</th><th>Date</th><th>Saved</th></tr></thead><tbody>${goalRows}</tbody></table>` : ""}
    <p style="margin-top:2rem;font-size:0.875rem;color:#64748b">Generated by MotionFi. Use Print → Save as PDF to export.</p>
  </body></html>`;
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => {
    win.print();
    win.close();
  }, 500);
}

function downloadBlob(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
